---
title: "SEIZ"
author: "Junwen Huang"
date: "2018/4/14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(pracma)
library(dplyr)
library(ggplot2)
```

```{r}
load("~/STA650/Final Project/Modeling/SEIZdataset_small_inconsN.Rdata")
data = cbind(SEIZ_df_s_ic[,1], SEIZ_df_s_ic[,3], SEIZ_df_s_ic[,4], SEIZ_df_s_ic[,2], SEIZ_df_s_ic[,5])
```

```{r}
derivative = function(y, para){
  S = y[1]  
  E = y[2]
  I = y[3]
  Z = y[4]
  
  beta = para[1]
  b = para[2]
  p = para[3]
  l = para[4]
  rho = para[5]
  epsilon = para[6]
  
  npop = S+E+I+Z
  dS = (-beta*S*I - b*S*Z)/npop        
  dE = (1-p)*beta*S*I/npop + (1-l)*b*S*Z/npop - rho*E*I/npop - epsilon*E
  dI = p*beta*S*I/npop + rho*E*I/npop + epsilon*E
  dZ = l*b*S*Z/npop
  
  vout = c(dS, dE, dI, dZ)
  
  return(vout)
}
```

```{r}
recurrence = function(f, dt, T, y0, para){
  tout = seq(T[1], T[2], by = dt)
  yout = matrix(0, length(tout), 4)
  yout[1,] = y0
  
  for(j in 2:length(tout)){
    former = yout[j-1,]
    d = f(former, para)
    new = dt * d + former
    yout[j,] = new
  }
  
  out = cbind(tout, yout)
  
  return(out)
}
```

```{r}
error = function(para){
  
  pred = recurrence(derivative, dt, c(time[1], time[length(time)]), c(S0, E0, I0, Z0), para)
  S = pred[,2]
  E = pred[,3]
  I = pred[,4]
  Z = pred[,5]
  
  index = which(pred[,1] %in% time)
  sub = c(S[index], E[index], I[index], Z[index])
  # sub = I[index]
  
  true = c(data[, 2] %>% as.numeric(), data[, 3] %>% as.numeric(), data[, 4] %>% as.numeric(), data[, 5] %>% as.numeric())
  # true = data[, 4] %>% as.numeric()
  abs_error = abs(sub - true)
  return(abs_error)
}
```

```{r}
dt = 1
data = as.matrix(data)
time = 1:length(data[,1])
S0 = data[1,2] %>% as.numeric()
E0 = data[1,3] %>% as.numeric()
I0 = data[1,4] %>% as.numeric()
Z0 = data[1,5] %>% as.numeric()
para = rep(0, 6)
fit = lsqnonlin(error, para)
para = fit$x
pred = recurrence(derivative, dt, c(time[1], time[length(time)]), c(S0, E0, I0, Z0), para)
SEIZ_whole = as.data.frame(pred)
colnames(SEIZ_whole) = c("hour", "S_n", "E_n", "I_n", "Z_n")
```

```{r}
save(SEIZ_whole, file = "SEIZ_whole.Rdata")
```

